// setters for bucket state
export const MOVIES_PREFIX = `MOVIES`;
export const GET_MOVIE_LIST = `${MOVIES_PREFIX}.GET_MOVIE_LIST`;
export const SET_MOVIE_LIST = `${MOVIES_PREFIX}.SET_MOVIE_LIST`;
export const SET_MOVIE_LIST_TOTALS = `${MOVIES_PREFIX}.SET_MOVIE_LIST_TOTALS`;
export const SET_MOVIE_LIST_FINDBY = `${MOVIES_PREFIX}.SET_MOVIE_LIST_FINDBY`;
export const HANDLE_ERROR = `${MOVIES_PREFIX}.HANDLE_ERROR`;

export const SEARCH_MOVIES = `${MOVIES_PREFIX}.SEARCH_MOVIES`;
export const CHANGE_PAGE = `${MOVIES_PREFIX}.CHANGE_PAGE`;

export const SET_ERROR = `${MOVIES_PREFIX}.SET_ERROR`;
